markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: 'Ushering In Growth'
description: "My development story begins here."

# Author's info
author: 'Jordan Taylor'
# edit 'categories' in the front matter of every post to match this username
nickname: jt
bio: 'Software Engineer. DC. Radford Baseball Alum.'
location: 'Virginia, USA'
url: 'https://jt.codes/'
image: 'assets/images/kube-gopher.png'

short_url: 'jt.codes'
google_analytics: UA-81287416-1
disqus:
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title/
# permalink: /author/:username
# permalink: /tag/:tag

# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: captjt
repo: site
branch: master
relative_source: ./
destination: ./site-pages/
production_url:  https://jt.codes
source_url:      https://github.com/captjt/site/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
